### ISSUE TITLE
The test that comparea a set of **some-numbers** with a set of (cdr **some-numbers**) fails if the car appears in the cdr

### ISSUE THREAD

**Issue by Yehouda** [danshapero/cl-dict#3]
Inside the test set-equality, this form 

  
`(is-false (set-eq (apply 'set-insert (cons (empty-set) some-numbers))
                    (apply 'set-insert (cons (empty-set) (cdr some-numbers)))))`

may fail if the **car** of **some-numbers** appears in the **cdr** of it. Since **some-numbers** is made of random numbers, that can happen (the probability is around 10%).

**Comment by danshapero** [comment]
Wow that is embarrassing! This should be fixed by 7a99eaaca1f952029def9ad5a2b80a612a712208 which replaces the second set by one with an extra value that's outside the numerical range of the randomly-generated list. Thanks for catching this!
