### ISSUE TITLE
Fails to compile on ABCL 1.8 because of cl-murmurhash

### ISSUE THREAD

**Issue by mdbergmann** [danshapero/cl-dict#4]
See: https://github.com/ruricolist/cl-murmurhash/issues/10

**Comment by danshapero** [comment]
Thanks for reporting this Manfred! I'm not sure what to do here. On the one hand, we could wait until this gets fixed upstream. On the other hand, I only pulled in that dependency to hash things -- I could just as easily use another package or maybe even write something myself. What do you think?

**Comment by mdbergmann** [comment]
The author of cl-murmurhash has made a workaround.
So I think there is nothing to be done here. Will be available with the next quicklisp update only, but at least it's documented.
Thanks.
